config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    resources :lyrics do
      collection do
        get "import" => "lyrics#raw_new", as: :raw_new
        post "import" => "lyrics#raw_create", as: :raw_create
        get "edit_all" => "lyrics#edit_all", as: :edit_all
        match "destroy_all" => "lyrics#destroy_all", as: :destroy_all, via: [:get, :delete]
      end
    end

    resource :verse_references do
      collection do
        match "destroy_general" => "verse_references#destroy_general", as: :destroy_general, via: [:get, :delete]
      end
    end
  end

  get "song(.format)" => "pages#song"
  get "index(.format)" => "pages#index"

  root to: "pages#index"
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  def index
  end

  def raw_new
  end

  def raw_create
    SongLyric.import_from_raw_lyrics(song: song, raw_lyrics: params.require(:song).require(:raw_lyrics))
    redirect_to song_path(song, anchor: "lyrics")
  end

  def edit_all
  end

  def destroy_all
    song.sections.destroy_all
    redirect_to song_path(song, anchor: "lyrics")
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  helper_method \
  def song
    @song ||= Song.find_by_id(params[:song_id].to_i)
  end
end

app/views/lyrics/_line.html.slim
.row
  .large-12.columns
    = lyric.line

app/views/lyrics/_section.html.slim
.row
  .large-1.column
  .large-11.columns
    h4 = section.name
    = render partial: "lyrics/line", collection: section.lyrics, as: :lyric
br

app/views/lyrics/_section_form.html.slim
.row
  .large-12.columns
    // # TOOD: add a real section form

app/views/lyrics/edit_all.html.slim
.row
  .large-12.columns
    .row
      .large-12.columns
        h1
          =' song.title
          small - Edit Lyrics
    .row
      .large-12.columns
        = render partial: "section_form", collection: song.lyric_sections, as: :section
        = link_to "Cancel", song_path(song), class: "button secondary"

app/views/lyrics/raw_new.html.slim
.row
  .large-12.columns
    .row
      .large-12.columns
        h1
          =' song.title
          small - Add lyrics
    hr
    = simple_form_for(song, url: raw_create_song_lyrics_path(song), method: "POST") do |f|
      = f.input :raw_lyrics, as: :text, input_html: { rows: 20 }
      = f.button :submit, "Add Song Lyrics"