config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    resources :lyrics do
      collection do
        get "import" => "lyrics#raw_new", as: :raw_new
        post "import" => "lyrics#raw_create", as: :raw_create
        get "edit_all" => "lyrics#edit_all", as: :edit_all
        match "destroy_all" => "lyrics#destroy_all", as: :destroy_all, via: [:get, :delete]
      end
    end

    resource :verse_references do
      collection do
        match "destroy_general" => "verse_references#destroy_general", as: :destroy_general, via: [:get, :delete]
      end
    end
  end

  get "song(.format)" => "pages#song"
  get "index(.format)" => "pages#index"

  root to: "pages#index"
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :sections, class_name: "SongSection", dependent: :destroy
  has_many :lyrics, class_name: "SongLyric"

  has_many :verse_references, class_name: "SongLyricVerseReference"
  has_many :general_verse_references, -> { where(song_section_id: nil, song_lyric_id: nil) }, class_name: "SongLyricVerseReference", dependent: :destroy
  has_many :section_verse_references, through: :sections, class_name: "SongLyricVerseReference"
  has_many :lyric_verse_references, through: :lyrics, class_name: "SongLyricVerseReference"

  validates :title, :artist, presence: true

  attr_accessor :raw_lyrics, :general_references

  def self.from_search(search_text)
    verse_range = VerseRange.parse(search_text) rescue nil
    if verse_range
      from_verse_range(verse_range)
    else
      from_text_search(search_text)
    end
  end

  def self.from_verse_range(verse_range)
    Song
      .distinct
      .joins(:verse_references)
      .merge(SongLyricVerseReference.intersects_range(verse_range))
  end

  def self.from_text_search(search_text)
    like_match = "%#{search_text}%"
    Song
      .distinct
      .joins(:lyrics)
      .where("title LIKE ? OR artist LIKE ? OR line LIKE ?", like_match, like_match, like_match)
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end

  def rating
    super.to_i
  end

  def star_rating
    StarRating.new(rating)
  end

  def tempo
    "#{bpm} Beats per Minute"
  end

  def full_lyrics
    return nil unless sections.present?

    sections.map { |section| section.lyrics.map(&:line).join("\n") }.join("\n\n")
  end

  def as_json(options = {})
    super(options || {})
      .merge(
        lyrics: full_lyrics,
        general_references: general_verse_references.map(&:to_h)
      )
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: :api_call?

  def index
    respond_to do |format|
      format.html
      format.json { render json: songs.to_a }
    end
  end

  def new
    @song = Song.new
  end

  def create
    general_references = params[:song][:general_references]
    raw_lyrics = params[:song][:raw_lyrics]
    @song = Song.create(song_params)
    if song.persisted?
      if raw_lyrics.present?
        ImportsRawLyrics.new(song: @song, raw_lyrics: raw_lyrics).call
      end

      if general_references.present?
        SongLyricVerseReference.import_raw_general_references(song: @song, general_references: general_references)
      end
      return redirect_to song_path(song)
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: song }
    end
  end

  def edit
  end

  def update
    song.update(song_params)
    return redirect_to song_path(song) if song.valid?
  end

  def destroy
    song.destroy
    redirect_to songs_path
  end

  private

  def api_call?
    params[:api_key] == "shibboleet"
  end

  def song_params
    params.required(:song).permit(:title, :artist, :video_url, :bpm, :time_signature, :release_year, :rating)
  end

  helper_method \
  def songs
    @songs ||=
      if params[:q].present?
        Song.from_search(params[:q])
      else
        Song.all
      end.page(page).per(per)

  end

  helper_method \
  def song
    @song ||= Song.find_by_id(params[:id].to_i)
  end
end

app/views/songs/_details_tab.html.slim
.row
  .large-4.columns
    = key_value_row("Tempo:", song.tempo)
    = key_value_row("Time Signature:", song.time_signature)
    = key_value_row("Released:", song.release_year)
    = key_value_row("Rating:", song.star_rating)
  .large-8.columns.text-center
    - if song.video_url.present?
      .row
        .large-12.columns.text-center
          iframe width="560" height="315" src=song.video_url frameborder="0" allowfullscreen=""

app/views/songs/_form.html.slim
.row
  .large-12.columns
    = simple_form_for(song) do |f|
      = f.input :title
      = f.input :artist
      = f.input :video_url
      = f.input :bpm
      = f.input :time_signature
      = f.input :release_year, min: 0, max: Date.today.year
      = f.input :rating, collection: (0..5).map { |rating| [StarRating.new(rating), rating]}, as: :radio_buttons, container_html: { class: "horizontal" }
      hr
      - unless song.persisted?
        = f.input :general_references, as: :text
        = f.input :raw_lyrics, as: :text, input_html: { rows: 20 }
        hr
      .row
        .large-1.columns
          = link_to "Cancel", song.persisted? ? song_path(song) : songs_path, class: "button secondary"
        .large-1.columns
          = f.button :submit

app/views/songs/_list_item.html.slim
.row
  .large-6.columns = song.title
  .large-4.columns = song.artist
  .large-2.columns
    =' link_to "Details", song_path(song)
    =' link_to "Edit", edit_song_path(song)
    = link_to "Delete", song_path(song), method: :delete

app/views/songs/_lyrics_tab.html.slim
.row
  .large-12.columns
    .row
      .large-8.columns
      - if song.sections.present?
        .large-2.columns
        /=' link_to "Edit Lyrics", edit_all_song_lyrics_path(song), class: "button secondary"
        .large-2.columns
          = link_to "Delete Lyrics", destroy_all_song_lyrics_path(song), class: "button alert", data: { confirm: "Are you sure?" }
      - else
        .large-4.columns.text-left
          = link_to "Add Lyrics", raw_new_song_lyrics_path(song), class: "button primary"
    .row
      .large-12-columns
        - if song.sections.present?
          = render partial: "lyrics/section", collection: song.sections, as: :section
        - else
          p No Lyrics Found

app/views/songs/_verse_reference.html.slim
.row
  .large-12.columns
    h4 = verse_reference.to_s
    p = verse_reference.verse_text

app/views/songs/_verses_tab.html.slim
.row
  .large-12.columns
    .row
      .large-8.columns
        h3 General Verse References for this Song
      - if song.general_verse_references.present?
        .large-2.columns
          = link_to "Add Verse References", new_song_verse_references_path(song), class: "button primary"
        .large-2.columns
          = link_to "Delete All General Verse References", destroy_general_song_verse_references_path(song), class: "button alert", data: { confirm: "Are you sure?" }
      - else
        .large-4.columns.text-right
          = link_to "Add Verse References", new_song_verse_references_path(song), class: "button primary"
    .row
      .large-12-columns
        - if song.general_verse_references.present?
          = render partial: "verse_reference", collection: song.general_verse_references, as: :verse_reference
        - else
          p No Verse References Found

app/views/songs/edit.html.slim
.row
  .large-12.columns
    h1 Update this song!
    = render partial: "form"

app/views/songs/index.html.slim
.row
  .large-12.columns
    .row
      .large-10.columns
        h1 All the Songs
      .large-2.columns
        = link_to "Add Song", new_song_path, class: "button primary"
    hr
    = form_tag songs_path, method: :get do
      .row
        .large-10.columns
          = search_field_tag :q, params[:q]
        .large-2.columns
          = submit_tag "Search", class: "button primary"
    .row
      .large-6.columns
        h4.show-for-large Title
        h4.hide-for-large Song Info
      .large-4.columns.show-for-large
        h4 Artist
      .large-2.columns.show-for-large
        h4 Actions
    = render(partial: "list_item", collection: songs, as: :song)

app/views/songs/new.html.slim
.row
  .large-12.columns
    h1 Sing a new Song!
    = render partial: "form"

app/views/songs/show.html.slim
.row
  .large-12.columns
    .row
      .large-12.columns
        .row
          .large-8.columns
            nav role="navigation"
              ul.breadcrumbs
                li = link_to "Songs", songs_path
                li = link_to song.title, song_path(song)
          .large-2.columns
            = link_to "Edit Song", edit_song_path(song), class: "button secondary"
          .large-2.columns
            =' link_to "Delete Song", song_path(song), method: :delete, data: { confirm: "Are you sure you want to delete this song?" }, class: "button alert"
    hr
    .row
      .large-12.columns
        h1
          =' song.title
          small = song.artist
    .tabs data-deep-link="true" data-tabs="" id="song_tabs"
      .tabs-title.is-active
        = link_to("Details", "#details")
      .tabs-title
        = link_to("Lyrics", "#lyrics")
      .tabs-title
        = link_to("Verses", "#verses")
    .tabs-content data-tabs-content="song_tabs"
      .tabs-panel.is-active id="details"
        = render partial: "details_tab"
      .tabs-panel id="lyrics"
        = render partial: "lyrics_tab"
      .tabs-panel id="verses"
        = render partial: "verses_tab"